#+TITLE:     shell-extras-leuven
#+AUTHOR:    Fabrice Niessen
#+EMAIL:     (concat "fniessen" at-sign "pirilampo.org")
#+DESCRIPTION: Shell extra utilities
#+KEYWORDS:  shell, script, bash
#+OPTIONS:   num:nil

Shell extra utilities

* Notes

Why write an entire bash script in functions?
https://unix.stackexchange.com/questions/313256/why-write-an-entire-bash-script-in-functions

** Usage

docopt for shell - make beautiful CLI with ease
https://github.com/docopt/docopts

(I choose for the "with grep" syntax to have the help and version messages
parsed from script *comments*, while avoiding having to source =docopts.sh=.)

** Coding style

- Beautiful Bash: Let's make reading and writing bash scripts fun again!
  https://fr.slideshare.net/a_z_e_t/inpresentation

- Let's make better scripts
  https://downloads.cisofy.com/files/public/presentation-lets-make-better-scripts.pdf

- http://wiki.bash-hackers.org/scripting/style

- https://github.com/azet/community_bash_style_guide

- https://google-styleguide.googlecode.com/svn/trunk/shell.xml

  ~variable_name~ (preferred, ~variableName~ accepted) \\
  ~function_name~ \\
  ~CONSTANT_NAME~

** Shell formatter + checker

- https://github.com/mvdan/sh
- https://google.github.io/styleguide/shell.xml
- https://www.shellcheck.net/ (online checker!)

http://www.skybert.net/emacs/bash-linting-in-emacs/

* bak

Create a quick back-up copy of a file.

* f

Find directories or files matching a string and print their full file name.

* fd

Find directories matching a string and print their full file name.

* ff

Find files matching a string and print their full file name.

* swap

Swap the contents of two files.
